/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(enterprise)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(enterprise)'}/issue` | `/issue`; params?: Router.UnknownInputParams; } | { pathname: `${'/(enterprise)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(enterprise)'}/verify` | `/verify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(enterprise)'}/workers` | `/workers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/receive` | `/receive`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/create-wallet`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/import-wallet`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/role-selection`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/wallet-ready`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(enterprise)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(enterprise)'}/issue` | `/issue`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(enterprise)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(enterprise)'}/verify` | `/verify`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(enterprise)'}/workers` | `/workers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(worker)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(worker)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(worker)'}/receive` | `/receive`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/create-wallet`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/import-wallet`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/role-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/wallet-ready`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(enterprise)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(enterprise)'}/issue${`?${string}` | `#${string}` | ''}` | `/issue${`?${string}` | `#${string}` | ''}` | `${'/(enterprise)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(enterprise)'}/verify${`?${string}` | `#${string}` | ''}` | `/verify${`?${string}` | `#${string}` | ''}` | `${'/(enterprise)'}/workers${`?${string}` | `#${string}` | ''}` | `/workers${`?${string}` | `#${string}` | ''}` | `${'/(worker)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(worker)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(worker)'}/receive${`?${string}` | `#${string}` | ''}` | `/receive${`?${string}` | `#${string}` | ''}` | `/onboarding/create-wallet${`?${string}` | `#${string}` | ''}` | `/onboarding/import-wallet${`?${string}` | `#${string}` | ''}` | `/onboarding/role-selection${`?${string}` | `#${string}` | ''}` | `/onboarding/wallet-ready${`?${string}` | `#${string}` | ''}` | `/onboarding/welcome${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(enterprise)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(enterprise)'}/issue` | `/issue`; params?: Router.UnknownInputParams; } | { pathname: `${'/(enterprise)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(enterprise)'}/verify` | `/verify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(enterprise)'}/workers` | `/workers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(worker)'}/receive` | `/receive`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/create-wallet`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/import-wallet`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/role-selection`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/wallet-ready`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
